services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - webnet

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_fpm
    volumes:
      - ./:/var/www/html
    networks:
      - webnet

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clonusly
      MYSQL_USER: clonusly
      MYSQL_PASSWORD: clonuslypw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  mysql_data:

networks:
  webnet:
